before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: I36qCfZ2DIWTxavmg1M4YCBLLi0IiMD6tlIEtjpI1eLPWrMxChPpFkcI5yeGk5teCfb0tCO8gxSfxsuuCxswNyS7/s01qhKbSKXjOyxn2qaN6T3IkmtiXzVYFJBl61xxkkROk6BpYpLs3WlhS/aHBVRtsx/r/3RRMBp/uYJPBn0iV/RSmJdSnn5qOtm1rrqrt6qvjwZWFDXGdRFsdjvEytKmJ3XuSyl/X1X8dx0ayNN5HpiwaxeWg7RA3JNV/y3eblTKGN5pWK61yLP+iHkvN+y76qlv5K8Zf1PvSlkyW+7DQWI/po2f/PHcFXGOcd+c8VJ1hNHGp5G6+peUsTOzR8Kl/VfAkKIcDzUSvL7+3/+Ce54OLXUOpjQAizCT68eV03roQryALhK3hTscR3fWGXLJ0iYbIaEd3VRDmKITlaDxyuol5lkDV1vRM4YOxkjbTXVgT1uFSVRloI7Co2gC906sXHwaEwobKblMHyfYsJEjMvukc8a8oqRlyIybsDwvL/HoDFlFHbny/wUIBcypJ+WmaNUJaXuUcQeF5bO1SFlnT5B6GwzkGQvqy5X70au9UirUzsW6JliAF+/z4ceveod5ZO1XT4Zj6+zBMdSduiVDPQ+Ju2EJMMQQiqV7+LqepanuWrkwHiiJ+NyJIBCfR0OSIz+BuE3th6sgiAV4GP0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
